baseURL = "https://www.lakurdinawebsite.github.io/"
languageCode = "en-gb"
title = "Welcome to Lakurdina"
theme = "hugograyscale"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    # Provide some metadata for search and indexing services
    description = "The Lakurdina Main Site"

[Author]
    name = "Lakurdina"
    #email = ""

[Social]
    #twitter = ""
